% run from C:/Users/silbaugh/Desktop/Abby folder
% only 'figs' folder can exist in 20230516_analysis folder
%clear all
        %% process confocal data %%
        % runterminaldensity
        %% preprocess cerebellum two photon data %%
        cbdata = processcb;
        %% set stimulus frame by mouse
%         artifactframes = [];
%         save('20250724_artifactframes.mat', 'artifactframes')
        %% compile S1 two photon data
        addpath('20230516_analysis');
        allData = compileDataset;
        %% set neuron colors and mice
        neuron_colors = {[188,5,66]/255, [22,109,42]/255, [44,55,113]/255,  [0, 0, 0]/255, [92,2,86]/255};
        neuron_names = {'PV', 'PN', 'VIP', 'UC', 'SST'};
        load('setmice.mat')
        %% manually inspect stimulus artifact frame
        % removeartifact
        %% ignore plasticity induction trials
        allData = removetettrials(allData);
        %% interpolate optical stimulus artifact
        allData = interpartifact_new(allData, NaN);
        allData = interpbaselineartifact(allData, 'noplot'); 
        % visualizeartifactremoval(allData)
        %% perform background subtraction
        allData = backgroundsubtract(allData, 'noplot');
        % visualizerawdata(allData)
        % visualizerawdata_eachcell(allData, 49, 'rawminusfirstprctile')
        %% smooth traces and express as ΔF/F0
        F0_percent = 1;
        smooth_win = 15;
        allData = getGOLAY_new(allData, F0_percent, 10, smooth_win, 'rawminusfirstprctile');
        % visualizesmoothing(allData);
        %% set motion detection parameters (M, NM, T, H trials; binary rest/running trials)
        rest_period = 12;
        NM_thresh = [0, 0];
        T_thresh = [0, 1]; 
        M_thresh = [1, 1];
        H_thresh = [1, 0];
        prestim_win = [290 305];
        poststim_win = [305 336];
        allData = getrest(allData, rest_period);
        allData = gettransition(allData, prestim_win, poststim_win, NM_thresh, T_thresh, M_thresh, H_thresh, 'noplot');
        %% set pre-stimulus normalization period and threshold
        baselinenormperiod = [300, 305];
        baselinenorm = 1;
        baseline_reject_thresh = [NaN, 5];
        %% calculate baseline noise (σ) and SNR
        noise_prc = 1;
        sig_prc = 95;
        [baselineNoise, SNR] = getbaselinenoise_fast(allData, noise_prc, sig_prc, 'golaysignal3', 10);
%% PLOT σ and SNR
        [~] = visualizeSNR(allData, SNR, baselineNoise, 21, 40, neuron_colors);
        %% perform oasis deconvolution (find spikes)
        sn_thresh_3 = 3;
        allData = runoasis(allData, baselineNoise, false, sn_thresh_3, 'golaysignal3');
        %% correlate cell with motion
        [allData] = getcellxmotion(allData, 'motion', 'golaysignal3');
        [allData] = cellxmotion_prepost(allData, 'excludedcz');
        [allData] = getmotcells(allData, 0.1, 'correlation');
%% PLOT neural correlation with motion behavior
        [~] = visualizemotioncorrelation(allData, 0.1, 40, 'PRE', neuron_colors);
        %% find peaks
        peaks_thr = 3; 
        [allData] = getpeaks_new(allData, peaks_thr, NaN, baselineNoise, 310, 'golaysignal3', 'noplot');
%% PLOT evoked event window
        std_thresh = 3;
        [peak_win, spike_win] = visualizealleventsbymouse(allData, std_thresh, ''); % UPDATED CODE 20250825
        %% grab evoked events (based on spike or peak window)
        [allData] = getwindowevents(allData, spike_win, peak_win);
        [allData] = getevokedtraces_byspike(allData, spike_win);
        [allData] = getevokedtraces_bypeak(allData, peak_win); 
        %% analyze spontaneous rest/run conditions (spike rate and mean dF/F0)
        [allData] = getspontinfo(allData, spike_win);
         %% calculate ROI size
         [roi_sizes] = calculateROIsize(allData);
        %% set window for AUC, maximum calculations
        stim_onset = 301;
        auc_max_win = [306, 328];
        trace_window = [280, 367];
        %% set time window for analysis
        [allData] = settimewindow(allData, -50, 60, -50, 50);
%%
load('setmice13.mat')
setmice = setmice13;
        %% FIGURE 1, S1, S2, S3
        %% Purkinje cell responses to CF stimulation
            plotcbdata(cbdata, auc_max_win)
        %% Maximum and area under the curve (by neuron) pre- and post- plasticity
            % Persistent cells (Figure 1.G, 1.J)
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces_settime';
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            % Grab only the neurons responsive both pre and post 
            [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, ...
            RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');

%             visualizetracesPVandSST(neuron_colors, trace_window, [-0.01, 0.2], stim_onset, ...
%             RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');

             plotauc_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 6.5])
%            plotauc_byneuron_box(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 12])
%            plotauc_byneuron_combineSSTandPV(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 3])
%            plotmax_byneuron_bar(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, .45])
%%
        % Persistent, recruited, and suppressed cells (Fig S2.C)
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces_settime'; % evokedtraces, evokedtraces2, golaysignal, golaysignal2, golaysignal3, golaysignal4, golayshift
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);
            
            [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post] = visualizeortraces(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, ...
            RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');

%           visualizeortracesPVandSST(neuron_colors, trace_window, [-0.01, 0.2], stim_onset, ...
%           RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');

            plotauc_byneuron_unpaired(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 6])
%           plotmax_byneuron_bar(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 0.5])

            plotpie(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors)
%%
        % All traces (includes traces not meeting evoked event criteria) (S2.D-I)
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'golaysignal3_settime'; % evokedtraces, evokedtraces2, golaysignal, golaysignal2, golaysignal3, golaysignal4, golayshift
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post] = visualizeortraces(neuron_colors, trace_window, [-0.1, 0.2], stim_onset, ...
            RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');
           
%           visualizeortracesPVandSST(neuron_colors, trace_window, [-0.01, 0.2], stim_onset, ...
%           RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');

            plotauc_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 2])
%           plotauc_byneuron_combineSSTandPV(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 2])
%           plotmax_byneuron_bar(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 0.5])
        %% Area under the curve across time (persistent cells)
            mottype = 'all';
            tracetype = 'evokedtraces_settime'; % evokedtraces, evokedtraces2
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
            false, false, mottype, allData, tracetype, setmice);
%%
            figure('Position', [350,429,314,183])
            [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'PN');
            timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'PN', neuron_colors, [0, 10.5], 'ploterrorbars', [2, 12], 12, 'persistent');
%%
            figure('Position', [350,429,314,183])
            [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'UC');
            timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'UC', neuron_colors, [0, 10.5], 'ploterrorbars', [2, 12], 12, 'persistent');

%           figure('Position', [350,429,314,183])
%           [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'SST and PV');
%           timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'SST and PV', neuron_colors, [0, 10.5], 'ploterrorbars', [2, 12], 10, 'persistent');

%           figure('Position', [350,429,314,183])
%           [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'SST');
%           timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'SST', neuron_colors, [0, 10.5], 'ploterrorbars', [2, 12], 10, 'persistent');
%  
%           figure('Position', [350,429,314,183])
%           [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'PV');
%           timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'PV', neuron_colors, [0, 10.5], 'ploterrorbars', [2, 12], 12, 'persistent');
% 
%            figure('Position', [350,429,314,183])
%            [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'VIP');
%            timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'VIP', neuron_colors, [0, 10.5], 'ploterrorbars', [2, 12], 11, 'persistent');
%% Area under the curve across time (all cells and traces)
            mottype = 'all';
            tracetype = 'golaysignal3_settime'; % evokedtraces, evokedtraces2
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
            false, false, mottype, allData, tracetype, setmice);

            figure('Position', [166,575,300,183]);
            [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'PN');
            timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'PN', neuron_colors, [0, 3.75], 'ploterrorbars', [2, 12], 12, '');

             figure('Position', [166,575,300,183]);
             [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre,RWS_post, RWSCF_pre, RWSCF_post, 'UC');
             timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'UC', neuron_colors, [0, 3.75], 'ploterrorbars', [2, 12], 12, '');

%              figure('Position', [166,575,300,183]);
%             [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'SST and PV');
%             timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'SST and PV', neuron_colors, [0, 3.75], 'ploterrorbars', [2, 12], 12, '');

            figure('Position', [166,575,300,183]);
            [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre,RWS_post, RWSCF_pre, RWSCF_post, 'SST');
            timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'SST', neuron_colors, [0, 3.75], 'ploterrorbars', [2, 12], 12, '');
 
            figure('Position', [166,575,300,183]);
            [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre,RWS_post, RWSCF_pre, RWSCF_post, 'PV');
            timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'PV', neuron_colors, [0, 3.75], 'ploterrorbars', [2, 12], 12, '');
            
            figure('Position', [166,575,300,183]);
            [binned_RWS, binned_RWSCF] = parsetime(mottype, allData, setmice.RWS_mice, setmice.RWSCF_mice, RWS_pre,RWS_post, RWSCF_pre, RWSCF_post, 'VIP');
            timegraph_auc(binned_RWS, binned_RWSCF, auc_max_win, 'VIP', neuron_colors, [0, 3.75], 'ploterrorbars', [2, 12], 12, '');
            %% Max and area under the curve (by mouse) pre- and post- plasticity (persistent cells)
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces_settime'; % evokedtraces, evokedtraces2, golaysignal, golaysignal2, golaysignal3, golaysignal4, golayshift
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, false, mottype, allData, tracetype, setmice);

            %plotauc_bymouseV2(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 10.5], 'persistent', 'paired')
            plotauc_bymouseV2(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 2], 'persistent', 'normalized')
            %plotauc_bymouseV2_combineSST_PV(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0.4, 2], 'persistent', 'normalized')
%% FIGURE 2
        %% Maximum and area under the curve (by neuron) to W and W+CF stimuli
        % PN, IN, and VIP cells (only those responsive to both W and W+CF)
            load('setmice11.mat')
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
            [pre, pre_wo, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice11);

            % Grab only the neurons responsive both pre and pre_wo
            [pre, pre_wo] = visualizeandtracesBT(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, ...
            pre, pre_wo, 'yesplot');

            plotauc_byneuronBT(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, 5], 'pairedstats')
            %plotauc_byneuronBT_box(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, 5], 'pairedstats')
            %plotmax_byneuronBT(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, .3], 'pairedstats')
            %plotmax_byneuronBT_box(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, .71], 'pairedstats')
%%
            % Additional auc_max_win analysis window

            visualizeandtracesBT_windows(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, pre, pre_wo, 'yesplot', auc_max_win, [326, 332]);
           plotauc_byneuronBT(pre, pre_wo, neuron_colors, [326, 332], {'W', 'W+CF'}, [0, 5], 'pairedstats');
%%
            % SST and PV neurons (only those responsive to both W and W+CF)
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
            [pre, pre_wo, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            % Grab only the neurons responsive both pre and pre_wo
            [pre, pre_wo] = visualizeandtracesBT(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, ...
            pre, pre_wo, 'yesplot');

%             [pre, pre_wo] = visualizeortracesBT(neuron_colors, trace_window, [0, 0.35], stim_onset, ...
%             pre, pre_wo, 'yesplot');

            plotauc_byneuronBT(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, 5], 'pairedstats')
            %plotauc_byneuronBT_box(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, 5], 'pairedstats')
            %plotmax_byneuronBT(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, .3], 'pairedstats')
            %plotmax_byneuronBT_box(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, .71], 'pairedstats')
        %% Maximum and area under the curve (by mouse) to W and W+CF stimuli
            % PN, IN, and VIP neurons
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
            [pre, pre_wo, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, false, mottype, allData, tracetype, setmice11);

            %plotauc_bymouseBT(pre, pre_wo, neuron_colors, 0, auc_max_win, {'W', 'W + CF'}, [0.5, 15], 'persistent', 'paired')
            plotauc_bymouseBT(pre, pre_wo, neuron_colors, 0, auc_max_win, {'W', 'W + CF'}, [0.5, 1.75], 'persistent', 'normalize')
%%
            % SST and PV neurons
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
            [pre, pre_wo, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, false, mottype, allData, tracetype, setmice);

            %plotauc_bymouseBT(pre, pre_wo, neuron_colors, 0, auc_max_win, {'W', 'W + CF'}, [0.5, 10], 'persistent', 'paired')
            plotauc_bymouseBT(pre, pre_wo, neuron_colors, 0, auc_max_win, {'W', 'W + CF'}, [0.5, 1.75], 'persistent', 'normalize')
%% FIGURE 3
        %% Maximum and area under the curve (by neuron) pre- and post- plasticity
            % Combine pre periods (pre, pre_dcz)
            % PN neurons
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces';
            [~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, ...
            control_SST_Gi_pre_comb, control_SST_Gi_post, ...
            RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, ...
            control_SST_Gq_pre_comb, control_SST_Gq_post,...
            ~, ~, ...
            ~, ~, ... 
            ~, ~, ...
            ~, ~]...
            = parsetraces3(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);
            
            % Grab only the neurons responsive to both conditions
            [control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.7], stim_onset, ...
            control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, 'yesplot');
            
            [control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.7], stim_onset, ...
            control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, 'yesplot');
%%
            %plotauc_byneuron_violin(control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [-0.1, 17])
            %plotauc_byneuron_violin(control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [-0.1, 17])
            plotauc_byneuron(control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, neuron_colors, 0, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [0, 12])
            plotauc_byneuron(control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, neuron_colors, 0, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [0, 12])
            plotmax_byneuron(control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, neuron_colors, 0, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [0, 1.2])
            plotmax_byneuron(control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, neuron_colors, 0, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [0, 1.2])
%%
        % SST neurons
        % Add control mice to plasticity group for analysis
        % Expt 2 statistics are relevant
            load('setmice12.mat')
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces';
            [~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, ...
            control_SST_Gi_pre_comb, control_SST_Gi_post, ...
            RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, ...
            control_SST_Gq_pre_comb, control_SST_Gq_post,...
            ~, ~, ...
            ~, ~, ... 
            ~, ~, ...
            ~, ~]...
            = parsetraces3(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice12);
            
            % Grab only the neurons responsive to both conditions
            [control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.7], stim_onset, ...
            control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, 'yesplot');
            
            [control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.7], stim_onset, ...
            control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, 'yesplot');

            %plotauc_byneuron_violin(control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [-0.1, 17])
            %plotauc_byneuron_violin(control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [-0.1, 17])
            plotauc_byneuron(control_SST_Gq_pre_comb, control_SST_Gq_post, RWS_SST_Gq_pre_comb, RWS_SST_Gq_post, neuron_colors, 0, [306, 360], {'+SST', 'RWS+SST'}, {'Pre', 'DCZ'}, [0, 12])
            plotauc_byneuron(control_SST_Gi_pre_comb, control_SST_Gi_post, RWSCF_SST_Gi_pre_comb, RWSCF_SST_Gi_post, neuron_colors, 0, [306, 360], {'-SST', 'RWSCF-SST'}, {'Pre', 'DCZ'}, [0, 12])
%% FIGURE 4
        %% Maximum and area under the curve (by neuron) pre- and post- plasticity
            % Combine pre periods (pre, pre_dcz)
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces';
            [~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~,...
            RWSCF_VIP_Gq_pre_comb, RWSCF_VIP_Gq_post, ...
            control_VIP_Gq_pre_comb, control_VIP_Gq_post, ... 
            RWS_VIP_Gi_pre_comb, RWS_VIP_Gi_post, ...
            control_VIP_Gi_pre_comb, control_VIP_Gi_post]...
            = parsetraces3(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            % Grab only the neurons responsive both pre and post 
            [control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb, RWS_VIP_Gi_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.6], stim_onset, ...
            control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb, RWS_VIP_Gi_post, 'yesplot');
            
            [control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb, RWSCF_VIP_Gq_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.6], stim_onset, ...
            control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb, RWSCF_VIP_Gq_post, 'yesplot');


            %plotauc_byneuron_violin(control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [-0.1, 6.5])
            %plotauc_byneuron_violin(control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [-0.1, 6.5])
            plotauc_byneuron(control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb, RWS_VIP_Gi_post, neuron_colors, 0, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [0, 6.5])
            plotauc_byneuron(control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb, RWSCF_VIP_Gq_post, neuron_colors, 0, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [0, 6.5])
            plotmax_byneuron(control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb, RWS_VIP_Gi_post, neuron_colors, 0, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [0, 0.4])
            plotmax_byneuron(control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb, RWSCF_VIP_Gq_post, neuron_colors, 0, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [0, 0.4])
%%
         % VIP neurons
         % Plot DCZ wash-in for control experiments
         % Expt1 statistics are relevant
            mottype = 'all';
            tracetype = 'golaysignal3';
            [~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            RWSCF_VIP_Gq_pre, ~, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, ...
            control_VIP_Gq_pre, ~, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, ... 
            RWS_VIP_Gi_pre, ~, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, ...
            control_VIP_Gi_pre, ~, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            [control_VIP_Gi_pre, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_post] = visualizeandtraces(neuron_colors, [290, 367], [0, 0.45], stim_onset, ...
            control_VIP_Gi_pre, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_post, 'yesplot');
            [control_VIP_Gq_pre, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post] = visualizeandtraces(neuron_colors, [290, 367], [0, 0.45], stim_onset, ...
            control_VIP_Gq_pre, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post, 'yesplot');

            plotauc_byneuron(control_VIP_Gi_pre, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_post, neuron_colors, 0, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'DCZ'}, [0, 6.5])
            plotauc_byneuron(control_VIP_Gq_pre, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post, neuron_colors, 0, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'DCZ'}, [0, 6.5]);

            % Additional auc_max_win analysis window (similar to Figure 2)
            plotauc_byneuron(control_VIP_Gi_pre, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_post, neuron_colors, 0, [327, 333], {'-VIP', 'RWS-VIP'}, {'Pre', 'DCZ'}, [0, 6.5])
            plotauc_byneuron(control_VIP_Gq_pre, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post, neuron_colors, 0, [327, 333], {'+VIP', 'RWSCF+VIP'}, {'Pre', 'DCZ'}, [0, 6.5]);
%% FIGURE S? Additional VIP data
%% Maximum and area under the curve (by neuron) pre- and post- plasticity
            % Combine pre periods (pre, pre_dcz)
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces';
            [~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~, ...
            ~, ~,...
            RWSCF_VIP_Gq_pre_comb, RWSCF_VIP_Gq_post, ...
            control_VIP_Gq_pre_comb, control_VIP_Gq_post, ... 
            RWS_VIP_Gi_pre_comb, RWS_VIP_Gi_post, ...
            control_VIP_Gi_pre_comb, control_VIP_Gi_post]...
            = parsetraces3(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            temp_block = [2, 21, 60, 66, 91, 103, 119, 122, 127, 130, 131, 133, 136, 137, 138, 139, 141, 142, 145, 146, 154, 156, 159, 160, 161, 162, 165];
            temp_rescue = [1, 2, 28, 29, 30, 32, 34, 36, 40, 45, 54, 56, 62, 64, 67, 69, 75, 78, 80, 85, 90, 93, 96, 97, 98, 101, 103, 104, 105, 107, 108, 109, 112, 113, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 134, 136, 137, 140, 141, 143, 144, 145, 147, 149, 150, 151, 153, 154, 155, 156, 157, 160, 170, 171, 176, 177, 181, 182, 184, 186, 189, 192, 193, 194, 196, 199, 201, 205, 206, 208, 209, 211, 212, 213, 214, 215, 218, 220, 223, 226, 228, 231, 232, 234, 236, 237, 238, 241];
            
                        
            RWS_VIP_Gi_pre_comb_2 = cell(1, 5);
            RWS_VIP_Gi_post_2 = cell(1, 5);
            temp_pre = RWS_VIP_Gi_pre_comb{4};
            temp_pre = temp_pre(:, temp_block);
            temp_post = RWS_VIP_Gi_post{4};
            temp_post = temp_post(:, temp_block);
            RWS_VIP_Gi_pre_comb_2{4} = temp_pre;
            RWS_VIP_Gi_post_2{4} = temp_post;
            
            RWSCF_VIP_Gq_pre_comb_2 = cell(1, 5);
            RWSCF_VIP_Gq_post_2 = cell(1, 5);
            temp_pre = RWSCF_VIP_Gq_pre_comb{4};
            temp_pre = temp_pre(:, temp_rescue);
            temp_post = RWSCF_VIP_Gq_post{4};
            temp_post = temp_post(:, temp_rescue);
            RWSCF_VIP_Gq_pre_comb_2{4} = temp_pre;
            RWSCF_VIP_Gq_post_2{4} = temp_post;

            [control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb_2, RWS_VIP_Gi_post_2] = visualizeortraces(neuron_colors, trace_window, [-0.1, 0.6], stim_onset, ...
            control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb_2, RWS_VIP_Gi_post_2, 'yesplot');
            
            [control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb_2, RWSCF_VIP_Gq_post_2] = visualizeortraces(neuron_colors, trace_window, [-0.1, 0.6], stim_onset, ...
            control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb_2, RWSCF_VIP_Gq_post_2, 'yesplot');

            plotauc_byneuron(control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb_2, RWS_VIP_Gi_post_2, neuron_colors, 0, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb_2, RWSCF_VIP_Gq_post_2, neuron_colors, 0, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [0, 4.5])

            plotmax_byneuron(control_VIP_Gi_pre_comb, control_VIP_Gi_post, RWS_VIP_Gi_pre_comb_2, RWS_VIP_Gi_post_2, neuron_colors, 0, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [0, 0.4])
            plotmax_byneuron(control_VIP_Gq_pre_comb, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_comb_2, RWSCF_VIP_Gq_post_2, neuron_colors, 0, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [0, 0.4])
            
%% FIGURE 5
        %% Maximum and area under the curve (by neuron) to W and W+CF stimuli, before and after DCZ admin
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
            [~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, ...
            PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo]...
            = parsetraces(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            % Grab only the neurons responsive to all conditions: pre (W and W+CF) and after DCZ admin (W and W+CF)
%             [SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.61], stim_onset, ...
%             SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, 'yesplot');

            [PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.61], stim_onset, ...
            PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo, 'yesplot');

            %plotauc_byneuron(SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, neuron_colors, 0, auc_max_win,  {'Pre', 'DCZ'}, {'W', 'W+CF'}, [-0.1, 17])
            plotauc_byneuron(PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo, neuron_colors, 0, auc_max_win,   {'Pre', 'DCZ'}, {'W', 'W+CF'}, [0, 6])
            %plotmax_byneuron(SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, neuron_colors, 0, auc_max_win,   {'Pre', 'DCZ'}, {'W', 'W+CF'}, [-0.1, 17])
            %plotmax_byneuron(PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo, neuron_colors, 1, auc_max_win,  {'Pre', 'DCZ'}, {'W', 'W+CF'}, [0, .65])
            %plotmax_byneuron_bar(SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, neuron_colors, 0, auc_max_win,  {'Pre', 'DCZ'}, {'W', 'W+CF'}, [0, .5])
            %plotmax_byneuron_bar(PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo, neuron_colors, 0, auc_max_win,  {'Pre', 'DCZ'}, {'W', 'W+CF'}, [0, .5])

%% Figure S3 (plasticity in rest and active states)
        %% Behavioral data
            visualizemotion_new(allData, 'NM', prestim_win, poststim_win, '', [248, 372], 'motionInfo_settime')
            visualizemotion_new(allData, 'MT', prestim_win, poststim_win, '', [248, 372], 'motionInfo_settime')
           %%
            % Proportion of rest, run, transition, halt trials
            [proportion_mot_trials] = visualizemotion_byperiod(allData, [279, 372], '', '', 'motionInfo_settime');
            % Combine run and transition trials
            plotmotionproportion(proportion_mot_trials, setmice.RWS_mice, setmice.RWSCF_mice, 'pre_w', 'post', 'combineactive')
%%
            % Motion traces (active state)
             mottype = 'MT'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
            [~, ~, ...
            RWS_pre_MT, ~, RWS_post_MT, ...
            RWSCF_pre_MT, ~, RWSCF_post_MT, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsemottraces(true, true, mottype, allData, setmice, 'motionInfo_settime');

            visualizemottraces(trace_window, [-0.05, 1.1], stim_onset, RWS_pre_MT, RWS_post_MT, RWSCF_pre_MT, RWSCF_post_MT, 'yesplot', 'MT')
%%
            % Motion traces (rest state)
            mottype = 'NM'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
            [~, ~, ...
            RWS_pre_NM, ~, RWS_post_NM, ...
            RWSCF_pre_NM, ~, RWSCF_post_NM, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsemottraces(true, true, mottype, allData, setmice, 'motionInfo_settime');

            visualizemottraces(trace_window, [-0.05, 1.1], stim_onset, RWS_pre_NM, RWS_post_NM, RWSCF_pre_NM, RWSCF_post_NM, 'yesplot', 'NM')
        %% Maximum and area under the curve (by neuron) pre- and post- plasticity
            % Active state
            mottype = 'MT'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
            tracetype = 'evokedtraces_settime';
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);
            
            % Grab only the neurons responsive both pre and post 
            [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, ...
            RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');

            plotauc_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 7.5])
            % plotmax_byneuron_bar(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, .45])
%%
            % Rest state
            mottype = 'NM'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
            tracetype = 'evokedtraces_settime';
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);
            
            % Grab only the neurons responsive both pre and post 
            [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.45], stim_onset, ...
            RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');

            plotauc_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 7.5])
            % plotmax_byneuron_bar(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, .45])
       %%
%              % Motion trials
%             mottype = 'M'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
%             tracetype = 'evokedtraces_settime';
%             [~, ~, ...
%             RWS_pre, ~, RWS_post, ...
%             RWSCF_pre, ~, RWSCF_post, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~,...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
%             false, true, mottype, allData, tracetype, setmice);
%             
%             % Grab only the neurons responsive both pre and post 
%             [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, ...
%             RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');
% 
%             plotauc_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 7.5])
%             % plotmax_byneuron_bar(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, .45])
% 
%             % Transition trials
%             mottype = 'T'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
%             tracetype = 'evokedtraces_settime';
%             [~, ~, ...
%             RWS_pre, ~, RWS_post, ...
%             RWSCF_pre, ~, RWSCF_post, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~,...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
%             false, true, mottype, allData, tracetype, setmice);
%             
%             % Grab only the neurons responsive both pre and post 
%             [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post] = visualizeandtraces(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, ...
%             RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, 'yesplot');
% 
%             plotauc_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 7.5])
%             % plotmax_byneuron_bar(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, .45])
        %% Max and area under the curve (by mouse) pre- and post- plasticity
            % Active state
            mottype = 'MT'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces_settime'; % evokedtraces, evokedtraces2, golaysignal, golaysignal2, golaysignal3, golaysignal4, golayshift
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, false, mottype, allData, tracetype, setmice);

            %plotauc_bymouseV2(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 10.5], 'persistent', 'paired')
            plotauc_bymouseV2(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0.4, 2], 'persistent', 'normalize')
%%
            % Rest state
            mottype = 'NM'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces_settime'; % evokedtraces, evokedtraces2, golaysignal, golaysignal2, golaysignal3, golaysignal4, golayshift
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, false, mottype, allData, tracetype, setmice);

            %plotauc_bymouseV2(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 10.5], 'persistent', 'paired')
            plotauc_bymouseV2(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0.4, 2], 'persistent', 'normalized')
            %% Percent active trials versus ∆AUC
            % Grab active evoked events
            mottype = 'MT'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
            tracetype = 'evokedtraces_settime';
            [~, ~, ...
            RWS_pre_MT, ~, RWS_post_MT, ...
            RWSCF_pre_MT, ~, RWSCF_post_MT, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
            false, false, mottype, allData, tracetype, setmice);

            % Grab all evoked events
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H', 'MT'
            tracetype = 'evokedtraces_settime';
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
            false, false, mottype, allData, tracetype, setmice);

            % Calculate percent active trials for each cell
            [RWS_prctactive, RWSCF_prctactive] = calculatepercentactive(RWS_pre, RWS_pre_MT, RWS_post, RWS_post_MT, RWSCF_pre, RWSCF_pre_MT, RWSCF_post, RWSCF_post_MT);

            % Keep only persistent cells
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'evokedtraces_settime';
            [~, ~, ...
            RWS_pre, ~, RWS_post, ...
            RWSCF_pre, ~, RWSCF_post, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            % Grab only the neurons responsive both pre and post 
            [RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, RWS_prctactive, RWSCF_prctactive] = keeppersistent(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, RWS_prctactive, RWSCF_prctactive);

            plotauc_prctactive_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, RWS_prctactive, RWSCF_prctactive, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 6], '')
            %% Figure SX (chemogenetic manipulation controls)
%%
        % PV neurons
        % Plot the neurons responsive pre, after DCZ administration, and post together
            mottype = 'all';
            tracetype = 'evokedtraces';
            [pre, pre_wo, ...
    RWS_pre, RWS_pre_wo, RWS_post, ...
    RWSCF_pre, RWSCF_pre_wo, RWSCF_post, ...
    RWSCF_PV_JAWS_pre, RWSCF_PV_JAWS_pre_wo, RWSCF_PV_JAWS_post, ...
    control_PV_JAWS_pre, control_PV_JAWS_pre_wo, control_PV_JAWS_post, ...
    RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_wo, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post, ...
    control_PV_Gi_pre, control_PV_Gi_pre_wo, control_PV_Gi_pre_dcz, control_PV_Gi_post, ...
    RWS_PV_Gq_pre, RWS_PV_Gq_pre_wo, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post, ...
    control_PV_Gq_pre, control_PV_Gq_pre_wo, control_PV_Gq_pre_dcz, control_PV_Gq_post, ...
    RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_wo, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, ...
    control_SST_Gi_pre, control_SST_Gi_pre_wo, control_SST_Gi_pre_dcz, control_SST_Gi_post, ...
    RWS_SST_Gq_pre, RWS_SST_Gq_pre_wo, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, ...
    control_SST_Gq_pre, control_SST_Gq_pre_wo, control_SST_Gq_pre_dcz, control_SST_Gq_post,...
    RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_wo, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, ...
    control_VIP_Gq_pre, control_VIP_Gq_pre_wo, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, ... 
    RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_wo, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, ...
    control_VIP_Gi_pre, control_VIP_Gi_pre_wo, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, ...
    SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, ...
    PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo]...
            = parsetraces(baselinenormperiod, 0, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);

            %[control_PV_Gq_pre, control_PV_Gq_pre_DCZ, control_PV_Gq_post, RWS_PV_Gq_pre, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post] = visualizeandtraces3(neuron_colors, trace_window, [0, 0.7], stim_onset, ...
            %control_PV_Gq_pre, control_PV_Gq_pre_dcz, control_PV_Gq_post, RWS_PV_Gq_pre, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post, 'yesplot');
            %%
            [control_PV_Gi_pre, control_PV_Gi_pre_dcz, control_PV_Gi_post, RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post] = visualizeandtraces3(neuron_colors, trace_window, [-.2, .72], stim_onset, ...
            control_PV_Gi_pre, control_PV_Gi_pre_dcz, control_PV_Gi_post, RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post, 'yesplot');

            %plotauc_byneuron3(control_PV_Gq_pre, control_PV_Gq_pre_dcz, control_PV_Gq_post, RWS_PV_Gq_pre, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post, neuron_colors, 1, auc_max_win, {'+PV', 'RWS+PV'}, {'Pre' , 'DCZ', 'Post'}, [0, 5])
            plotauc_byneuron3(control_PV_Gi_pre, control_PV_Gi_pre_dcz, control_PV_Gi_post, RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post, neuron_colors, 1, auc_max_win, {'-PV', 'RWSCF-PV'}, {'Pre' , 'DCZ', 'Post'}, [0, 14])

            % Plot conditions separately
%             plotauc_byneuron(control_PV_Gq_pre, control_PV_Gq_pre_dcz, RWS_PV_Gq_pre, RWS_PV_Gq_pre_dcz, neuron_colors, 1, auc_max_win, {'+PV', 'RWS+PV'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
%             plotauc_byneuron(control_PV_Gq_pre_dcz, control_PV_Gq_post, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post, neuron_colors, 1, auc_max_win, {'+PV', 'RWS+PV'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
%             plotauc_byneuron(control_PV_Gq_pre, control_PV_Gq_post, RWS_PV_Gq_pre, RWS_PV_Gq_post, neuron_colors, 1, auc_max_win, {'+PV', 'RWS+PV'}, {'Pre', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_PV_Gi_pre, control_PV_Gi_pre_dcz, RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_dcz, neuron_colors, 1, auc_max_win, {'-PV', 'RWSCF-PV'}, {'Pre', 'Pre (DCZ)'}, [0, 15])
            plotauc_byneuron(control_PV_Gi_pre_dcz, control_PV_Gi_post, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post, neuron_colors, 1, auc_max_win, {'-PV', 'RWSCF-PV'}, {'Pre (DCZ)', 'Post'}, [0, 15])
            plotauc_byneuron(control_PV_Gi_pre, control_PV_Gi_post, RWSCF_PV_Gi_pre, RWSCF_PV_Gi_post, neuron_colors, 1, auc_max_win, {'-PV', 'RWSCF-PV'}, {'Pre', 'Post'}, [0, 15])
%%
        % SST neurons
        % Plot the neurons responsive pre, after DCZ administration, and post together
            mottype = 'all';
            tracetype = 'evokedtraces';
            [~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            RWSCF_SST_Gi_pre, ~, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, ...
            control_SST_Gi_pre, ~, control_SST_Gi_pre_dcz, control_SST_Gi_post, ... 
            RWS_SST_Gq_pre, ~, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, ...
            control_SST_Gq_pre, ~, control_SST_Gq_pre_dcz, control_SST_Gq_post,...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);
            
            [control_SST_Gq_pre, control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post] = visualizeandtraces3(neuron_colors, trace_window, [0, 0.7], stim_onset, ...
            control_SST_Gq_pre, control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, 'yesplot');
            
            [control_SST_Gi_pre, control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post] = visualizeandtraces3(neuron_colors, trace_window, [0, 0.7], stim_onset, ...
            control_SST_Gi_pre, control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, 'yesplot');

            plotauc_byneuron3(control_SST_Gq_pre, control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, neuron_colors, 0, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre' , 'DCZ', 'Post'}, [0, 5])
            plotauc_byneuron3(control_SST_Gi_pre, control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre' , 'DCZ', 'Post'}, [0, 5])
            %%
%             % Plot conditions separately
            plotauc_byneuron(control_SST_Gq_pre, control_SST_Gq_pre_dcz, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, neuron_colors, 0, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            plotauc_byneuron(control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_SST_Gq_pre, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_post, neuron_colors, 0, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_SST_Gi_pre, control_SST_Gi_pre_dcz, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, neuron_colors, 0, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            plotauc_byneuron(control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_SST_Gi_pre, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post, neuron_colors, 0, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [0, 2.5]);
 
            %plotmax_byneuron(control_SST_Gq_pre, control_SST_Gq_pre_dcz, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            %plotmax_byneuron(control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])            
            %plotmax_byneuron(control_SST_Gq_pre, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_post, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [0, 0.6])
            %plotmax_byneuron(control_SST_Gi_pre, control_SST_Gi_pre_dcz, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            %plotmax_byneuron(control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
            %plotmax_byneuron(control_SST_Gi_pre, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [0 0.3])
            %plotslopes_byneuron(control_SST_Gq_pre, control_SST_Gq_pre_dcz, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, neuron_colors, 0, auc_max_win)
            %plotslopes_byneuron(control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, neuron_colors, 0, auc_max_win)
            %plotslopes_byneuron(control_SST_Gi_pre, control_SST_Gi_pre_dcz, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, neuron_colors, 0, auc_max_win)
            %plotslopes_byneuron(control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, neuron_colors, 0, auc_max_win)
            %plotauc_byneuron_violin(control_SST_Gq_pre, control_SST_Gq_pre_dcz, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Pre (DCZ)'}, [-0.1, 12])
            %plotauc_byneuron_violin(control_SST_Gi_pre, control_SST_Gi_pre_dcz, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Pre (DCZ)'}, [-0.1, 12])
            %plotauc_byneuron_violin(control_SST_Gq_pre, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_post, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [-0.1, 3.1])
            %plotauc_byneuron_violin(control_SST_Gi_pre, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [-0.1, 3.1])
            %plotauc_byneuron_violin(control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [-0.1, 3.1])
            %plotauc_byneuron_violin(control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [-0.1, 3.1])
%%
        % VIP neurons
        % Plot the neurons responsive pre, after DCZ administration, and post together
            mottype = 'all';
            tracetype = 'evokedtraces';
            [~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~, ... 
            ~, ~, ~, ~, ...
            ~, ~, ~, ~,...
            RWSCF_VIP_Gq_pre, ~, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, ...
            control_VIP_Gq_pre, ~, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, ... 
            RWS_VIP_Gi_pre, ~, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, ...
            control_VIP_Gi_pre, ~, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, ...
            ~, ~, ~, ~, ...
            ~, ~, ~, ~]...
            = parsetraces(baselinenormperiod, 1, baseline_reject_thresh, true,...
            false, true, mottype, allData, tracetype, setmice);
            
            [control_VIP_Gi_pre, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_SST__Gq_pre_dcz, RWS_VIP_Gi_post] = visualizeandtraces3(neuron_colors, trace_window, [0, 0.31], stim_onset, ...
            control_VIP_Gi_pre, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, 'yesplot');
            
            [control_VIP_Gq_pre, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post] = visualizeandtraces3(neuron_colors, trace_window, [0, 0.31], stim_onset, ...
            control_VIP_Gq_pre, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, 'yesplot');
            
            plotauc_byneuron3(control_VIP_Gi_pre, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre' , 'DCZ', 'Post'}, [0, 5])
            plotauc_byneuron3(control_VIP_Gq_pre, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre' , 'DCZ', 'Post'}, [0, 5])
            %%
            % Plot conditions separately
            plotauc_byneuron(control_VIP_Gi_pre, control_VIP_Gi_pre_dcz, RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_dcz, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            plotauc_byneuron(control_VIP_Gi_pre_dcz, control_VIP_Gi_post, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_VIP_Gi_pre, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_VIP_Gq_pre, control_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_dcz, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            plotauc_byneuron(control_VIP_Gq_pre_dcz, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
            plotauc_byneuron(control_VIP_Gq_pre, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [0, 2.5])
          
            %plotmax_byneuron(control_VIP_Gi_pre, control_VIP_Gi_pre_dcz, RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_dcz, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            %plotmax_byneuron(control_VIP_Gi_pre_dcz, control_VIP_Gi_post, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
            %plotmax_byneuron(control_VIP_Gi_pre, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [0, 0.6])
            %plotmax_byneuron(control_VIP_Gq_pre, control_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_dcz, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Pre (DCZ)'}, [0, 3.5])
            %plotmax_byneuron(control_VIP_Gq_pre_dcz, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre (DCZ)', 'Post'}, [0, 3.5])
            %plotmax_byneuron(control_VIP_Gq_pre, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [0 0.3])
            %plotslopes_byneuron(control_VIP_Gi_pre, control_VIP_Gi_pre_dcz, RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_dcz, neuron_colors, 0, auc_max_win)
            %plotslopes_byneuron(control_VIP_Gi_pre_dcz, control_VIP_Gi_post, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, neuron_colors, 0, auc_max_win)
            %plotslopes_byneuron(control_VIP_Gq_pre, control_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_dcz, neuron_colors, 0, auc_max_win)
            %plotslopes_byneuron(control_VIP_Gq_pre_dcz, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, neuron_colors, 0, auc_max_win)
            %plotauc_byneuron_violin(control_VIP_Gi_pre, control_VIP_Gi_pre_dcz, RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_dcz, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Pre (DCZ)'}, [-0.1, 12])
            %plotauc_byneuron_violin(control_VIP_Gq_pre, control_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_dcz, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Pre (DCZ)'}, [-0.1, 12])
            %plotauc_byneuron_violin(control_VIP_Gi_pre, control_VIP_Gi_post, RWS_VIP_Gi_pre, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [-0.1, 3.1])
            %plotauc_byneuron_violin(control_VIP_Gq_pre, control_VIP_Gq_post, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [-0.1, 3.1])
            %plotauc_byneuron_violin(control_VIP_Gi_pre_dcz, control_VIP_Gi_post, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [-0.1, 3.1])
            %plotauc_byneuron_violin(control_VIP_Gq_pre_dcz, control_VIP_Gq_post, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [-0.1, 3.1])
%% Obsolete functions

%%
% % Evoked event probability
%     mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%     tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
%             [~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             RWSCF_SST_Gi_pre, ~, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, ...
%             control_SST_Gi_pre, ~, control_SST_Gi_pre_dcz, control_SST_Gi_post, ... 
%             RWS_SST_Gq_pre, ~, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, ...
%             control_SST_Gq_pre, ~, control_SST_Gq_pre_dcz, control_SST_Gq_post,...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
%             false, false, mottype, allData, tracetype, setmice);
% 
% %             ploteventprobability_byneuron(control_SST_Gq_pre, control_SST_Gq_pre_dcz, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, neuron_colors, 0, {'+SST', 'RWS+SST'}, {'Pre', 'Pre (DCZ)'})
% %             ploteventprobability_byneuron(control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, neuron_colors, 1, {'+SST', 'RWS+SST'}, {'Pre (DCZ)', 'Post'})
% %             ploteventprobability_byneuron(control_SST_Gq_pre, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_post, neuron_colors, 1, {'+SST', 'RWS+SST'}, {'Pre', 'Post'})
% %             ploteventprobability_byneuron(control_SST_Gi_pre, control_SST_Gi_pre_dcz, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, neuron_colors, 0, {'-SST', 'RWSCF-SST'},  {'Pre', 'Pre (DCZ)'})
% %             ploteventprobability_byneuron(control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, neuron_colors, 1, {'-SST', 'RWSCF-SST'},  {'Pre (DCZ)', 'Post'})
% %             ploteventprobability_byneuron(control_SST_Gi_pre, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post, neuron_colors, 1, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'})
% %             ploteventprobability_byneuron_3cond(control_SST_Gq_pre, control_SST_Gq_pre_dcz, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, neuron_colors, 0, 'PN', {'Control', 'RWS'})
% %             ploteventprobability_byneuron_3cond(control_SST_Gi_pre, control_SST_Gi_pre_dcz, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, neuron_colors, 0, 'PN', {'Control', 'RWSCF'})
% %%
% % Spontaneous activity
%     mottype = 'all';
%     tracetype = 'spont_rate';
%             [~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             RWSCF_SST_Gi_pre, ~, ~, RWSCF_SST_Gi_post, ...
%             control_SST_Gi_pre, ~, ~, control_SST_Gi_post, ... 
%             RWS_SST_Gq_pre, ~, ~, RWS_SST_Gq_post, ...
%             control_SST_Gq_pre, ~, ~, control_SST_Gq_post,...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
%             false, false, mottype, allData, tracetype, setmice);
% 
%     plotspont_byneuron(control_SST_Gq_pre, control_SST_Gq_post, RWS_SST_Gq_pre, RWS_SST_Gq_post, neuron_colors, 1, {'+SST', 'RWS+SST'}, {'Pre', 'Post'}, [-0.1, 3.1])
%     plotspont_byneuron(control_SST_Gi_pre, control_SST_Gi_post, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post, neuron_colors, 1, {'-SST', 'RWSCF-SST'}, {'Pre', 'Post'}, [-0.1, 3.1])

% %% (plasticity of inhibitory neurons)
%     mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%     tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2, golaysignal, golaysignal2, golaysignal3, golaysignal4, golayshift
%             [pre, pre_wo, ...
%             RWS_pre, RWS_pre_wo, RWS_post, ...
%             RWSCF_pre, RWSCF_pre_wo, RWSCF_post, ...
%             RWSCF_PV_JAWS_pre, RWSCF_PV_JAWS_pre_wo, RWSCF_PV_JAWS_post, ...
%             control_PV_JAWS_pre, control_PV_JAWS_pre_wo, control_PV_JAWS_post, ...
%             RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_wo, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post, ...
%             control_PV_Gi_pre, control_PV_Gi_pre_wo, control_PV_Gi_pre_dcz, control_PV_Gi_post, ...
%             RWS_PV_Gq_pre, RWS_PV_Gq_pre_wo, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post, ...
%             control_PV_Gq_pre, control_PV_Gq_pre_wo, control_PV_Gq_pre_dcz, control_PV_Gq_post, ...
%             RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_wo, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, ...
%             control_SST_Gi_pre, control_SST_Gi_pre_wo, control_SST_Gi_pre_dcz, control_SST_Gi_post, ... 
%             RWS_SST_Gq_pre, RWS_SST_Gq_pre_wo, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, ...
%             control_SST_Gq_pre, control_SST_Gq_pre_wo, control_SST_Gq_pre_dcz, control_SST_Gq_post,...
%             RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_wo, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, ...
%             control_VIP_Gq_pre, control_VIP_Gq_pre_wo, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, ... 
%             RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_wo, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, ...
%             control_VIP_Gi_pre, control_VIP_Gi_pre_wo, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, ...
%             SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, ...
%             PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
%             false, true, mottype, allData, tracetype, setmice);
% %%
%             % Visualize traces
%             visualizeparsedtraces_INs_RWS_RWSCF(neuron_colors, trace_window, [-0.1, 0.4], stim_onset, RWS_pre, RWS_pre_wo, RWS_post, ...
%             RWSCF_pre, RWSCF_pre_wo, RWSCF_post)
% 
% %%
%             % AUC, maximum, slope
%             plotauc_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 30])
%            %  plotmax_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [-0.1, 1])
%            %  plotslopes_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, auc_max_win)


% % Evoked activity
%     mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%     tracetype = 'evokedtraces2'; % evokedtraces, evokedtraces2
%             [pre, pre_wo, ...
%             RWS_pre, RWS_pre_wo, RWS_post, ...
%             RWSCF_pre, RWSCF_pre_wo, RWSCF_post, ...
%             RWSCF_PV_JAWS_pre, RWSCF_PV_JAWS_pre_wo, RWSCF_PV_JAWS_post, ...
%             control_PV_JAWS_pre, control_PV_JAWS_pre_wo, control_PV_JAWS_post, ...
%             RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_wo, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post, ...
%             control_PV_Gi_pre, control_PV_Gi_pre_wo, control_PV_Gi_pre_dcz, control_PV_Gi_post, ...
%             RWS_PV_Gq_pre, RWS_PV_Gq_pre_wo, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post, ...
%             control_PV_Gq_pre, control_PV_Gq_pre_wo, control_PV_Gq_pre_dcz, control_PV_Gq_post, ...
%             RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_wo, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, ...
%             control_SST_Gi_pre, control_SST_Gi_pre_wo, control_SST_Gi_pre_dcz, control_SST_Gi_post, ... 
%             RWS_SST_Gq_pre, RWS_SST_Gq_pre_wo, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, ...
%             control_SST_Gq_pre, control_SST_Gq_pre_wo, control_SST_Gq_pre_dcz, control_SST_Gq_post,...
%             RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_wo, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, ...
%             control_VIP_Gq_pre, control_VIP_Gq_pre_wo, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, ... 
%             RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_wo, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, ...
%             control_VIP_Gi_pre, control_VIP_Gi_pre_wo, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, ...
%             SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, ...
%             PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
%             false, false, mottype, allData, tracetype, setmice);
% 
%     ploteventprobability_byneuron_ZI(SST_Gi_ZI_pre, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz_wo, neuron_colors, 1)
%     ploteventprobability_byneuron_ZI(PV_Gi_ZI_pre, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz_wo, neuron_colors, 1)



% % Evoked activity
%     mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%     tracetype = 'evokedtraces2'; % evokedtraces, evokedtraces2
%             [pre, pre_wo, ...
%             RWS_pre, RWS_pre_wo, RWS_post, ...
%             RWSCF_pre, RWSCF_pre_wo, RWSCF_post, ...
%             RWSCF_PV_JAWS_pre, RWSCF_PV_JAWS_pre_wo, RWSCF_PV_JAWS_post, ...
%             control_PV_JAWS_pre, control_PV_JAWS_pre_wo, control_PV_JAWS_post, ...
%             RWSCF_PV_Gi_pre, RWSCF_PV_Gi_pre_wo, RWSCF_PV_Gi_pre_dcz, RWSCF_PV_Gi_post, ...
%             control_PV_Gi_pre, control_PV_Gi_pre_wo, control_PV_Gi_pre_dcz, control_PV_Gi_post, ...
%             RWS_PV_Gq_pre, RWS_PV_Gq_pre_wo, RWS_PV_Gq_pre_dcz, RWS_PV_Gq_post, ...
%             control_PV_Gq_pre, control_PV_Gq_pre_wo, control_PV_Gq_pre_dcz, control_PV_Gq_post, ...
%             RWSCF_SST_Gi_pre, RWSCF_SST_Gi_pre_wo, RWSCF_SST_Gi_pre_dcz, RWSCF_SST_Gi_post, ...
%             control_SST_Gi_pre, control_SST_Gi_pre_wo, control_SST_Gi_pre_dcz, control_SST_Gi_post, ... 
%             RWS_SST_Gq_pre, RWS_SST_Gq_pre_wo, RWS_SST_Gq_pre_dcz, RWS_SST_Gq_post, ...
%             control_SST_Gq_pre, control_SST_Gq_pre_wo, control_SST_Gq_pre_dcz, control_SST_Gq_post,...
%             RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_pre_wo, RWSCF_VIP_Gq_pre_dcz, RWSCF_VIP_Gq_post, ...
%             control_VIP_Gq_pre, control_VIP_Gq_pre_wo, control_VIP_Gq_pre_dcz, control_VIP_Gq_post, ... 
%             RWS_VIP_Gi_pre, RWS_VIP_Gi_pre_wo, RWS_VIP_Gi_pre_dcz, RWS_VIP_Gi_post, ...
%             control_VIP_Gi_pre, control_VIP_Gi_pre_wo, control_VIP_Gi_pre_dcz, control_VIP_Gi_post, ...
%             SST_Gi_ZI_pre, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_dcz_wo, ...
%             PV_Gi_ZI_pre, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_dcz_wo]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
%             false, false, mottype, allData, tracetype, setmice);
% 
%     ploteventprobability_byneuron_ZI(SST_Gi_ZI_pre, SST_Gi_ZI_pre_dcz, SST_Gi_ZI_pre_wo, SST_Gi_ZI_pre_dcz_wo, neuron_colors, 1)
%     ploteventprobability_byneuron_ZI(PV_Gi_ZI_pre, PV_Gi_ZI_pre_dcz, PV_Gi_ZI_pre_wo, PV_Gi_ZI_pre_dcz_wo, neuron_colors, 1)


% %% Combine pre_dcz, post
% % Population average traces
%     mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%     tracetype = 'evokedtraces';
%             [RWSCF_PV_Gi_pre, RWSCF_PV_Gi_post_comb, ...
%     control_PV_Gi_pre, control_PV_Gi_post_comb, ...
%     RWS_PV_Gq_pre, RWS_PV_Gq_post_comb, ...
%     control_PV_Gq_pre, control_PV_Gq_post_comb, ...
%     RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post_comb, ...
%     control_SST_Gi_pre, control_SST_Gi_post_comb, ...
%     RWS_SST_Gq_pre, RWS_SST_Gq_post_comb, ...
%     control_SST_Gq_pre, control_SST_Gq_post_comb,...
%     RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post_comb, ...
%     control_VIP_Gq_pre, control_VIP_Gq_post_comb, ... 
%     RWS_VIP_Gi_pre, RWS_VIP_Gi_post_comb, ...
%     control_VIP_Gi_pre, control_VIP_Gi_post_comb]...
%     = parsetraces3_v2(baselinenormperiod, 1, baseline_reject_thresh, true,...
%             false, true, mottype, allData, tracetype, setmice);
% %%
% % Grab only the neurons responsive both pre and after DCZ admin
% [control_VIP_Gi_pre, control_VIP_Gi_post_comb, RWS_VIP_Gi_pre, RWS_VIP_Gi_post_comb] = visualizeandtraces(neuron_colors, trace_window, [0, 0.61], stim_onset, ...
% control_VIP_Gi_pre, control_VIP_Gi_post_comb, RWS_VIP_Gi_pre, RWS_VIP_Gi_post_comb, 'yesplot');
% 
% [control_VIP_Gq_pre, control_VIP_Gq_post_comb, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post_comb] = visualizeandtraces(neuron_colors, trace_window, [0, 0.61], stim_onset, ...
% control_VIP_Gq_pre, control_VIP_Gq_post_comb, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post_comb, 'yesplot');
% 
% %%
% % Plot AUC
% plotauc_byneuron_violin(control_VIP_Gi_pre, control_VIP_Gi_post_comb, RWS_VIP_Gi_pre, RWS_VIP_Gi_post_comb, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'Post'}, [-0.1, 17])
% plotauc_byneuron_violin(control_VIP_Gq_pre, control_VIP_Gq_post_comb, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post_comb, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'Post'}, [-0.1, 17])
% %%
% plotauc_byneuron(control_VIP_Gi_pre, control_VIP_Gi_post_comb, RWS_VIP_Gi_pre, RWS_VIP_Gi_post_comb, neuron_colors, 1, auc_max_win, {'-VIP', 'RWS-VIP'}, {'Pre', 'DCZ'}, [0, 6])
% plotauc_byneuron(control_VIP_Gq_pre, control_VIP_Gq_post_comb, RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post_comb, neuron_colors, 1, auc_max_win, {'+VIP', 'RWSCF+VIP'}, {'Pre', 'DCZ'}, [0, 3.6])
%     
%     
    
    
    %%
% %% Combine pre_dcz, post
% % Population average traces
%     mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%     tracetype = 'evokedtraces';
%             [RWSCF_PV_Gi_pre, RWSCF_PV_Gi_post_comb, ...
%     control_PV_Gi_pre, control_PV_Gi_post_comb, ...
%     RWS_PV_Gq_pre, RWS_PV_Gq_post_comb, ...
%     control_PV_Gq_pre, control_PV_Gq_post_comb, ...
%     RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post_comb, ...
%     control_SST_Gi_pre, control_SST_Gi_post_comb, ...
%     RWS_SST_Gq_pre, RWS_SST_Gq_post_comb, ...
%     control_SST_Gq_pre, control_SST_Gq_post_comb,...
%     RWSCF_VIP_Gq_pre, RWSCF_VIP_Gq_post_comb, ...
%     control_VIP_Gq_pre, control_VIP_Gq_post_comb, ... 
%     RWS_VIP_Gi_pre, RWS_VIP_Gi_post_comb, ...
%     control_VIP_Gi_pre, control_VIP_Gi_post_comb]...
%     = parsetraces3_v2(baselinenormperiod, 1, baseline_reject_thresh, true,...
%             false, true, mottype, allData, tracetype, setmice);
% %%  
% % Grab only the neurons responsive both pre and after DCZ admin
% [control_SST_Gq_pre, control_SST_Gq_post_comb, RWS_SST_Gq_pre, RWS_SST_Gq_post_comb] = visualizeandtraces(neuron_colors, trace_window, [0, 0.61], stim_onset, ...
% control_SST_Gq_pre, control_SST_Gq_post_comb, RWS_SST_Gq_pre, RWS_SST_Gq_post_comb, 'yesplot');
% 
% [control_SST_Gi_pre, control_SST_Gi_post_comb, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post_comb] = visualizeandtraces(neuron_colors, trace_window, [0, 0.61], stim_onset, ...
% control_SST_Gi_pre, control_SST_Gi_post_comb, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post_comb, 'yesplot');
% %%
% % Plot AUC
% plotauc_byneuron_violin(control_SST_Gq_pre, control_SST_Gq_post_comb, RWS_SST_Gq_pre, RWS_SST_Gq_post_comb, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'DCZ'}, [-0.1, 17])
% plotauc_byneuron_violin(control_SST_Gi_pre, control_SST_Gi_post_comb, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post_comb, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'DCZ'}, [-0.1, 17])
% %%
% plotauc_byneuron(control_SST_Gq_pre, control_SST_Gq_post_comb, RWS_SST_Gq_pre, RWS_SST_Gq_post_comb, neuron_colors, 1, auc_max_win, {'+SST', 'RWS+SST'}, {'Pre', 'DCZ'}, [0, 2.3])
% plotauc_byneuron(control_SST_Gi_pre, control_SST_Gi_post_comb, RWSCF_SST_Gi_pre, RWSCF_SST_Gi_post_comb, neuron_colors, 1, auc_max_win, {'-SST', 'RWSCF-SST'}, {'Pre', 'DCZ'}, [0, 2.5])

    %%
% % Evoked activity
%     mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%     tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
%             [pre, pre_wo, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~,...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
%             false, false, mottype, allData, tracetype, setmice3);
% %%
%     ploteventprobability_byneuron(pre, pre_wo, pre, pre_wo, neuron_colors, 0,{'W', 'W+CF'}, {'W', 'W+CF'})
%%
%         % PN and IN cells (those responsive to W and/or W+CF)
%             load('setmice6.mat')
%             mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%             tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
%             [pre, pre_wo, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~,...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
%             false, true, mottype, allData, tracetype, setmice6);
% 
%             [pre, pre_wo] = visualizeortracesBT(neuron_colors, trace_window, [0, 0.35], stim_onset, ...
%             pre, pre_wo, 'yesplot');
% %%
%             %plotauc_byneuronBT(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, 3.5], 'unpairedstats')
%             %plotauc_byneuronBT_box(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, 3.5], 'unpairedstats')
%             plotmax_byneuronBT(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, .3], 'unpairedstats')
%             plotmax_byneuronBT_box(pre, pre_wo, neuron_colors, auc_max_win, {'W', 'W+CF'}, [0, .71], 'unpairedstats')


%%


            %plotslopes_byneuronBT(pre, pre_wo, pre, pre_wo, neuron_colors, 0, auc_max_win)
%%
% % % Individual neurons (VIP)
% visualizesmoothing_individualneurons(allData, 20, 'evokedtraces', [0, 1.7], [303 450], ...
% '', 'all', baselinenormperiod, baselinenorm, baseline_reject_thresh, neuron_colors, '', 3, 310, [3, 14])
% 
% % Individual neurons (SST)
% visualizesmoothing_individualneurons(allData, 33, 'evokedtraces', [0, 0.65], [303 350], ...
% '', 'all', baselinenormperiod, baselinenorm, baseline_reject_thresh, neuron_colors, '', 5, 310, [3, 14])
% 
% % Individual neurons (PV)
% visualizesmoothing_individualneurons(allData, 8, 'evokedtraces', [-0.05, .6], [303 350], ...
% '', 'all', baselinenormperiod, baselinenorm, baseline_reject_thresh, neuron_colors, '', 1, 310, [1, 5])
%%
% Behavioral data
%plotmotionproportion(proportion_mot_trials, setmice.BT_mice, setmice.BT_mice, 'pre_w', 'pre_wo')
%%
%% Example neurons
             visualizesmoothing_individualneurons(allData, 20, 'evokedtraces', [-.1, 1.7], [303 400], ...
             '', 'all', baselinenormperiod, baselinenorm, baseline_reject_thresh, neuron_colors, '', 3, 310, [3, 14])
%%

            visualizesmoothing_individualneurons_single(allData, 10, 'evokedtraces', [-1, 3], [304 400],'', 'all', baselinenormperiod, baselinenorm, baseline_reject_thresh,  121, neuron_colors, [15*620, (15*620)+9294], [61*620, (61*620)+9294], 4, auc_max_win);
%%
            for i = 1:141
            visualizesmoothing_individualneurons_single(allData, 2, 'evokedtraces', [-1, 3], [304 400],'', 'all', baselinenormperiod, baselinenorm, baseline_reject_thresh,  i, neuron_colors, [15*620, (15*620)+9294], [61*620, (61*620)+9294], 2, auc_max_win);
            end
%%
% %% Evoked event probability
%             mottype = 'all';
%             tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2
%                     [~, ~, ...
%                     RWS_pre, ~, RWS_post, ...
%                     RWSCF_pre, ~, RWSCF_post, ...
%                     ~, ~, ~, ...
%                     ~, ~, ~, ...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ... 
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~,...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ... 
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~, ...
%                     ~, ~, ~, ~]...
%                     = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, false,...
%                     false, false, mottype, allData, tracetype, setmice);
%         
%                     ploteventprobability_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, {'RWS', 'RWSCF'}, {'Pre', 'Post'})

%%
%% Spontaneous event rate
            mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
            tracetype = 'b_oasis';
                    [~, ~, ...
                    RWS_pre, ~, RWS_post, ...
                    RWSCF_pre, ~, RWSCF_post, ...
                    ~, ~, ~, ...
                    ~, ~, ~, ...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ... 
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~,...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ... 
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~, ...
                    ~, ~, ~, ~]...
                    = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
                    false, false, mottype, allData, tracetype, setmice);
                    
            plotspont_byneuron(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 0, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [-0.1, 1])
            %%

          % Max and area under the curve (by mouse) pre- and post-
          % plasticity (version 1)
%             mottype = 'all'; % 'all', 'NM', 'M', 'T', 'H'
%             tracetype = 'evokedtraces'; % evokedtraces, evokedtraces2, golaysignal, golaysignal2, golaysignal3, golaysignal4, golayshift
%             [~, ~, ...
%             RWS_pre, ~, RWS_post, ...
%             RWSCF_pre, ~, RWSCF_post, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~,...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ... 
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~, ...
%             ~, ~, ~, ~]...
%             = parsetraces(baselinenormperiod, baselinenorm, baseline_reject_thresh, true,...
%             true, true, mottype, allData, tracetype, setmice);
%             
%             plotauc_bymouse(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 11], 'normalize')
%             % plotmax_bymouse(RWS_pre, RWS_post, RWSCF_pre, RWSCF_post, neuron_colors, 1, auc_max_win, {'RWS', 'RWSCF'}, {'Pre', 'Post'}, [0, 11])